# Generated by Django 5.2.8 on 2025-11-18 12:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Announcement Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AnnouncementsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Announcements Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for single-day events.",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End time"),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Event Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Events Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 7),
                    ("welcome_message", 11),
                    ("quick_links", 17),
                    ("announcements", 20),
                    ("events", 28),
                    ("christian_values", 34),
                    ("academic_highlights", 40),
                    ("testimonial_slider", 47),
                    ("gallery_preview", 51),
                    ("cta_banner", 53),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The background image for the banner.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The main title for the banner.",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The subtitle or introductory text for the banner.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The text to display on the button.",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL the button should link to.",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 3), ("button_link", 4)]],
                        {"required": False},
                    ),
                    6: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 0.4,
                            "help_text": "The opacity of the dark overlay on the background image (0.0 for transparent, 1.0 for fully opaque).",
                            "max_value": 1,
                            "min_value": 0,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("title", 1),
                                ("subtitle", 2),
                                ("button", 5),
                                ("overlay_opacity", 6),
                            ]
                        ],
                        {"group": "Banners"},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the welcome message.",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "The main content of the welcome message.",
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "An optional image to display alongside the message.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("message", 9), ("image", 10)]],
                        {"group": "Content"},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "link",
                            "help_text": "The Font Awesome icon name (e.g., 'fa-link').",
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The text label for the link.", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "The URL for the link.", "required": True},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 12), ("label", 13), ("link", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("links", 16)]],
                        {"group": "Content"},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title for the announcements section.",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "help_text": "The maximum number of announcements to display.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("post_limit", 19)]],
                        {"group": "Content"},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title for the events section.",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The title of the event.", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "The date of the event.", "required": True},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "A brief description of the event.",
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "An optional link for more information about the event.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("event_title", 22),
                                ("date", 23),
                                ("description", 24),
                                ("link", 25),
                            ]
                        ],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("events", 27)]],
                        {"group": "Content"},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The Font Awesome icon name (e.g., 'fa-heart').",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The title of the value.", "required": True},
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "A brief description of the value.",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 29), ("title", 30), ("description", 31)]],
                        {},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("values", 33)]],
                        {"group": "Content"},
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "The image for the highlight.", "required": True},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The title of the highlight.", "required": True},
                    ),
                    37: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "A brief description of the highlight.",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 35), ("title", 36), ("description", 37)]],
                        {},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 39)]],
                        {"group": "Content"},
                    ),
                    41: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The photo of the person giving the testimonial.",
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The name of the person.", "required": True},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The role or position of the person (e.g., 'Parent', 'Student').",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial quote.", "required": True},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("photo", 41), ("name", 42), ("role", 43), ("quote", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("testimonials", 46)]],
                        {"group": "Carousels and Sliders"},
                    ),
                    48: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    49: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"help_text": "The images to display in the gallery preview."},
                    ),
                    50: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "help_text": "The number of columns to use for the gallery grid.",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("images", 49), ("columns", 50)]],
                        {"group": "Media"},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 3), ("button_link", 4)]],
                        {"required": True},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("title", 1),
                                ("subtitle", 2),
                                ("button", 52),
                            ]
                        ],
                        {"group": "Banners"},
                    ),
                },
                help_text="The main content of the page, composed of different content blocks.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro",
            field=models.CharField(
                blank=True,
                help_text="A brief introduction to the school.",
                max_length=250,
                null=True,
            ),
        ),
    ]
